//
//  PreWorkoutBriefView.swift
//  GymTracker
//
//  AI Pre-Workout Brief — shown between the user tapping "Start" and the
//  3-2-1 countdown. The coach generates a tight forecast for today's session
//  (readiness, target weights, technique focus) and the user can fire up to
//  5 follow-up questions before kicking off the workout.
//
//  Lifecycle is driven by `WorkoutManager.workoutState`:
//      .idle → (user taps Start) → .briefing → (user taps Поехали) → .countdown
//
//  The brief itself is generated by `AICoachStore.generatePreWorkoutBrief(...)`
//  which is idempotent per (program, day, calendar-day).
//

import SwiftUI
import SwiftData

struct PreWorkoutBriefView: View {

    @ObservedObject private var store = AICoachStore.shared
    @Environment(\.modelContext) private var modelContext
    @EnvironmentObject private var workoutManager: WorkoutManager

    @State private var draft: String = ""
    @FocusState private var inputFocused: Bool

    @Query private var briefMessages: [AICoachMessage]

    init() {
        let sig = AICoachStore.shared.lastBriefSignature
        let predicate = #Predicate<AICoachMessage> {
            $0.workoutSignature != nil && $0.workoutSignature == sig
        }
        _briefMessages = Query(
            filter: predicate,
            sort: [SortDescriptor(\AICoachMessage.timestamp, order: .forward)]
        )
    }

    private var canSend: Bool {
        store.canAskQuestion(mode: .pre)
            && !draft.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    var body: some View {
        ZStack {
            DesignSystem.Colors.background.ignoresSafeArea()
            LinearGradient(
                colors: [
                    DesignSystem.Colors.accentPurple.opacity(0.18),
                    DesignSystem.Colors.background
                ],
                startPoint: .top,
                endPoint: .bottom
            )
            .ignoresSafeArea()
            .frame(maxHeight: 320)
            .frame(maxHeight: .infinity, alignment: .top)

            VStack(spacing: 0) {
                topBar
                messages
                Divider().background(Color.white.opacity(0.05))
                inputBar
                ctaBar
            }
        }
        .onAppear { store.attach(modelContext) }
    }

    // MARK: - Top bar

    private var topBar: some View {
        HStack(spacing: 10) {
            Button {
                UIImpactFeedbackGenerator(style: .soft).impactOccurred()
                workoutManager.cancelBriefing()
            } label: {
                Image(systemName: "chevron.left")
                    .font(.system(size: 14, weight: .heavy))
                    .foregroundStyle(DesignSystem.Colors.primaryText)
                    .frame(width: 32, height: 32)
                    .background(Color.white.opacity(0.06))
                    .clipShape(Circle())
            }

            VStack(alignment: .leading, spacing: 2) {
                Text("Подготовка к тренировке".localized())
                    .font(DesignSystem.Typography.headline())
                    .foregroundStyle(DesignSystem.Colors.primaryText)
                if let day = workoutManager.selectedDay {
                    Text(day.name)
                        .font(.callout)
                        .foregroundStyle(DesignSystem.Colors.secondaryText)
                        .lineLimit(1)
                }
            }
            Spacer()

            Button {
                UIImpactFeedbackGenerator(style: .light).impactOccurred()
                workoutManager.proceedToCountdown()
            } label: {
                Text("Пропустить".localized())
                    .font(.system(size: 12, weight: .semibold))
                    .foregroundStyle(DesignSystem.Colors.tertiaryText)
                    .padding(.horizontal, 12)
                    .padding(.vertical, 6)
                    .background(Color.white.opacity(0.05))
                    .clipShape(Capsule())
            }
        }
        .padding(.horizontal, DesignSystem.Spacing.lg)
        .padding(.top, 14)
        .padding(.bottom, 6)
    }

    // MARK: - Messages

    private var messages: some View {
        ScrollViewReader { proxy in
            ScrollView {
                VStack(alignment: .leading, spacing: 14) {
                    heroBanner

                    if briefMessages.isEmpty && !store.isBriefing {
                        emptyHint
                    }

                    ForEach(briefMessages) { msg in
                        MessageBubble(message: msg)
                            .id(msg.id)
                    }

                    if store.isBriefing || store.isReplying {
                        TypingIndicator().id("typing")
                    }

                    if let err = store.lastError {
                        errorBanner(err)
                    }
                }
                .padding(.horizontal, DesignSystem.Spacing.lg)
                .padding(.top, DesignSystem.Spacing.md)
                .padding(.bottom, 12)
            }
            .onChange(of: briefMessages.count) { _, _ in
                withAnimation(.easeOut(duration: 0.25)) {
                    if let last = briefMessages.last {
                        proxy.scrollTo(last.id, anchor: .bottom)
                    }
                }
            }
            .onChange(of: store.isReplying) { _, replying in
                if replying { withAnimation { proxy.scrollTo("typing", anchor: .bottom) } }
            }
        }
    }

    private var heroBanner: some View {
        HStack(spacing: 12) {
            ZStack {
                Circle()
                    .fill(
                        LinearGradient(
                            colors: [DesignSystem.Colors.accentPurple, DesignSystem.Colors.neonGreen],
                            startPoint: .topLeading,
                            endPoint: .bottomTrailing
                        )
                    )
                    .frame(width: 56, height: 56)
                Image(systemName: "bolt.heart.fill")
                    .font(.system(size: 24, weight: .heavy))
                    .foregroundStyle(.black)
            }
            VStack(alignment: .leading, spacing: 2) {
                Text("Брифинг от коуча".localized())
                    .font(DesignSystem.Typography.title2())
                    .foregroundStyle(DesignSystem.Colors.primaryText)
                Text("Готовность · цели · фокус".localized())
                    .font(.callout)
                    .foregroundStyle(DesignSystem.Colors.secondaryText)
            }
            Spacer()
        }
        .padding(DesignSystem.Spacing.md)
        .background(
            LinearGradient(
                colors: [DesignSystem.Colors.accentPurple.opacity(0.20), Color.white.opacity(0.02)],
                startPoint: .topLeading,
                endPoint: .bottomTrailing
            )
        )
        .overlay(
            RoundedRectangle(cornerRadius: DesignSystem.CornerRadius.medium)
                .stroke(DesignSystem.Colors.accentPurple.opacity(0.35), lineWidth: 0.5)
        )
        .clipShape(RoundedRectangle(cornerRadius: DesignSystem.CornerRadius.medium))
    }

    private var emptyHint: some View {
        Text("Анализирую твой план и историю последних тренировок…".localized())
            .font(DesignSystem.Typography.body())
            .foregroundStyle(DesignSystem.Colors.secondaryText)
            .padding(DesignSystem.Spacing.md)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(DesignSystem.Colors.cardBackground.opacity(0.5))
            .clipShape(RoundedRectangle(cornerRadius: DesignSystem.CornerRadius.medium))
    }

    private func errorBanner(_ message: String) -> some View {
        HStack(alignment: .top, spacing: 10) {
            Image(systemName: "exclamationmark.triangle.fill")
                .foregroundStyle(.orange)
            Text(message)
                .font(.callout)
                .foregroundStyle(DesignSystem.Colors.primaryText)
            Spacer(minLength: 0)
        }
        .padding(DesignSystem.Spacing.md)
        .background(Color.orange.opacity(0.10))
        .overlay(
            RoundedRectangle(cornerRadius: DesignSystem.CornerRadius.medium)
                .stroke(Color.orange.opacity(0.35), lineWidth: 0.5)
        )
        .clipShape(RoundedRectangle(cornerRadius: DesignSystem.CornerRadius.medium))
    }

    // MARK: - Input

    private var inputBar: some View {
        VStack(spacing: 6) {
            counterRow

            HStack(spacing: 10) {
                ZStack(alignment: .topLeading) {
                    if draft.isEmpty {
                        Text(placeholderText)
                            .foregroundStyle(DesignSystem.Colors.tertiaryText)
                            .padding(.horizontal, 14)
                            .padding(.vertical, 10)
                            .allowsHitTesting(false)
                    }
                    TextEditor(text: $draft)
                        .focused($inputFocused)
                        .scrollContentBackground(.hidden)
                        .padding(.horizontal, 10)
                        .padding(.vertical, 4)
                        .frame(minHeight: 38, maxHeight: 110)
                        .foregroundStyle(DesignSystem.Colors.primaryText)
                        .disabled(!store.canAskQuestion(mode: .pre))
                }
                .background(Color.white.opacity(0.06))
                .clipShape(RoundedRectangle(cornerRadius: 18))
                .overlay(
                    RoundedRectangle(cornerRadius: 18)
                        .stroke(Color.white.opacity(0.08), lineWidth: 0.5)
                )

                Button(action: send) {
                    ZStack {
                        Circle()
                            .fill(canSend ? DesignSystem.Colors.neonGreen : Color.white.opacity(0.08))
                            .frame(width: 38, height: 38)
                        Image(systemName: store.isReplying ? "ellipsis" : "arrow.up")
                            .font(.system(size: 16, weight: .heavy))
                            .foregroundStyle(canSend ? .black : DesignSystem.Colors.tertiaryText)
                    }
                }
                .disabled(!canSend)
            }
            .padding(.horizontal, DesignSystem.Spacing.lg)
            .padding(.vertical, 8)
        }
        .background(.ultraThinMaterial)
    }

    private var placeholderText: String {
        if !store.hasInsight(for: .pre) {
            return "Дождись брифинга, потом спрашивай…".localized()
        }
        if store.questionsRemaining(mode: .pre) == 0 {
            return "Лимит вопросов до тренировки исчерпан.".localized()
        }
        return "Спроси перед тренировкой…".localized()
    }

    private var counterRow: some View {
        HStack(spacing: 8) {
            HStack(spacing: 4) {
                Image(systemName: "bubble.left.and.bubble.right.fill")
                    .font(.system(size: 9, weight: .bold))
                Text(String(format: "%d/%d ".localized(),
                            store.questionsRemaining(mode: .pre),
                            AICoachStore.maxPreQuestions) + "вопросов".localized())
                    .font(.system(size: 10, weight: .semibold))
            }
            .foregroundStyle(DesignSystem.Colors.neonGreen)
            .padding(.horizontal, 8)
            .padding(.vertical, 4)
            .background(DesignSystem.Colors.neonGreen.opacity(0.12))
            .clipShape(Capsule())

            if store.cooldownRemaining > 0 {
                HStack(spacing: 4) {
                    Image(systemName: "clock.fill")
                        .font(.system(size: 9, weight: .bold))
                    Text(String(format: "ещё %d сек".localized(), Int(ceil(store.cooldownRemaining))))
                        .font(.system(size: 10, weight: .semibold))
                }
                .foregroundStyle(.orange)
                .padding(.horizontal, 8)
                .padding(.vertical, 4)
                .background(Color.orange.opacity(0.12))
                .clipShape(Capsule())
            }

            Spacer()
        }
        .padding(.horizontal, DesignSystem.Spacing.lg)
    }

    // MARK: - CTA

    private var ctaBar: some View {
        VStack(spacing: 0) {
            Button(action: {
                UIImpactFeedbackGenerator(style: .heavy).impactOccurred()
                workoutManager.proceedToCountdown()
            }) {
                HStack(spacing: 8) {
                    Image(systemName: "bolt.fill")
                        .font(.system(size: 14, weight: .heavy))
                    Text("Поехали".localized())
                        .font(.system(.headline, design: .rounded, weight: .heavy))
                }
                .foregroundStyle(.black)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 14)
                .background(
                    LinearGradient(
                        colors: [DesignSystem.Colors.neonGreen, DesignSystem.Colors.neonGreen.opacity(0.85)],
                        startPoint: .topLeading,
                        endPoint: .bottomTrailing
                    )
                )
                .clipShape(RoundedRectangle(cornerRadius: 18, style: .continuous))
                .shadow(color: DesignSystem.Colors.neonGreen.opacity(0.4), radius: 16, y: 6)
            }
            .padding(.horizontal, DesignSystem.Spacing.lg)
            .padding(.top, 6)
            .padding(.bottom, 18)
        }
        .background(.ultraThinMaterial)
    }

    // MARK: - Actions

    private func send() {
        let text = draft.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty else { return }
        draft = ""
        inputFocused = false
        Task { await store.askFollowUp(text, mode: .pre) }
    }
}
